#!/usr/bin/bash

# PARAMETROS OBRIGATORIOS
#export SCRATCH60="/home/scratch60/vlira_20nov2023/"
export SCRATCH90="/home/scratch90/vlira_11fev2025/"

export DATA="2025-03-04"  #DATA=$(date "+%F") 

export OUTPUT_DIR="/home/scratch60/Result_GermlineCNV.${DATA}"
export INPUT_DIR="/home/SCRATCH90/rtorreglosa_12jan2024/preprocessing_READ_result/"

export JOBS=5
export MAXmem=100
export COPY_RATIO=5
export CUTOFF_AMP=0.5
export CUTOFF_DEL=-1

#TOOLS e DATABASES
export GATK="${SCRATCH90}/tools/gatk-4.6.0.0/./gatk"
export PICARD="java -jar ${SCRATCH90}/tools/picard-3.2.0/picard.jar"
export ANNOVAR="$SCRATCH90/tools/annovar/table_annovar.pl"

export REF_FASTA="/home/projects2/LIDO/molPathol/oncoseek/nextseq/hg38/Homo_sapiens_assembly38.fasta"
export ANNOVAR_DB="${SCRATCH90}/humandb/"
export TARGET="${SCRATCH90}/references/xgen-exome-research-panel-v2-targets-hg38.autossome.bed"
export dataSourcesFolder="/home/scratch90/vlira_05ago2024/references/funcotator_dataSources.v1.8.hg38.20230908s/"
export PON="/home/users/vlira/PanelOfNornal/PON.100COVID.100-eigensamples.hdf5"
export BLACKLIST="${SCRATCH90}/references/CNV_and_centromere_blacklist.hg38liftover.list"

export LOG_FILE="${OUTPUT_DIR}/Pipeline_GermlineCNV.${DATA}.log"
export ERROR_FILE="${OUTPUT_DIR}/ERROR_FILE.log"

mkdir ${OUTPUT_DIR}


step1_PreprocessIntervals (){
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step1_PreprocessIntervals  <<<  $(date) " >> ${LOG_FILE}

  ${GATK} --java-options "-Xmx${MAXmem}G"  PreprocessIntervals \
    -L ${TARGET} \
    -XL ${BLACKLIST} \
    -R ${REF_FASTA}\
    --bin-length 0 \
    --interval-merging-rule OVERLAPPING_ONLY \
    -O $OUTPUT_DIR/step1_PreprocessIntervals/targets.preprocessed.interval_list \
    2> $OUTPUT_DIR/step1_PreprocessIntervals/step1_PreprocessIntervals.log
}
export -f step1_PreprocessIntervals


step2_AnnotateIntervals (){
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step2_AnnotateIntervals  <<<  $(date) " >> ${LOG_FILE}

  ${GATK} --java-options "-Xmx${MAXmem}G" AnnotateIntervals \
    -R ${REF_FASTA}/Homo_sapiens_assembly38.fasta \
    -L $OUTPUT_DIR/step1_PreprocessIntervals/targets.preprocessed.interval_list \
    -XL ${BLACKLIST} \ 
    --interval-merging-rule OVERLAPPING_ONLY \
    -O $OUTPUT_DIR/step2_AnnotateIntervals/annotated_intervals.tsv \
    2> $OUTPUT_DIR/step2_AnnotateIntervals/step2_AnnotateIntervals.log
}
export -f step2_AnnotateIntervals


step3_CollectReadCounts (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step3_CollectReadCounts para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}

  ${GATK} --java-options "-Xmx${MAXmem}G" CollectReadCounts \
    -I $SAMPLE  \
    -L $OUTPUT_DIR/step1_PreprocessIntervals/targets.preprocessed.interval_list \
    -XL ${BLACKLIST} \
    --interval-merging-rule OVERLAPPING_ONLY \
    -O  $OUTPUT_DIR/step3_CollectReadCounts/${NAME}.counts.hdf5 \
    2> $OUTPUT_DIR/step3_CollectReadCounts/$NAME.log
}
export -f step3_CollectReadCounts


step4_DenoiseReadCounts (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step4_DenoiseReadCounts para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}


  ${GATK} --java-options "-Xmx${MAXmem}G" DenoiseReadCounts \
    -I $OUTPUT_DIR/step3_CollectReadCounts/${NAME}.counts.hdf5 \
    --annotated-intervals $OUTPUT_DIR/step2_AnnotateIntervals/annotated_intervals.tsv \
    --count-panel-of-normals ${PON} \
    --standardized-copy-ratios $OUTPUT_DIR/step4_DenoiseReadCounts/${NAME}.standardizedCR.tsv \
    --denoised-copy-ratios $OUTPUT_DIR/step4_DenoiseReadCounts/${NAME}.denoisedCR.tsv  2> $OUTPUT_DIR/step4_DenoiseReadCounts/$NAME.log
}
export -f step4_DenoiseReadCounts

step5_PlotDenoisedCopyRatios (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step5_PlotDenoisedCopyRatios para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}


  ${GATK} --java-options "-Xmx${MAXmem}G" PlotDenoisedCopyRatios \
    --standardized-copy-ratios $OUTPUT_DIR/step4_DenoiseReadCounts/${NAME}.standardizedCR.tsv \
    --denoised-copy-ratios $OUTPUT_DIR/step4_DenoiseReadCounts/${NAME}.denoisedCR.tsv \
    --sequence-dictionary ${REF_FASTA}/Homo_sapiens_assembly38.dict \
    --minimum-contig-length 46709983 \
    --output $OUTPUT_DIR/step5_PlotDenoisedCopyRatios/ \
    --output-prefix ${NAME}  2> $OUTPUT_DIR/step5_PlotDenoisedCopyRatios/$NAME.log
}
export -f step5_PlotDenoisedCopyRatios

step5_PlotDenoisedCopyRatios_DOCKER (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step5_PlotDenoisedCopyRatios_DOCKER para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}


  docker run \
    --rm \
    -v $OUTPUT_DIR/:/gatk/my_data \
    -v ${REF_FASTA}:/gatk/hg38/ \
    -u $(id -u):$(id -g) broadinstitute/gatk \
    gatk --java-options "-Xmx${MAXmem}G" PlotDenoisedCopyRatios \
    --standardized-copy-ratios /gatk/my_data/step4_DenoiseReadCounts/${NAME}.standardizedCR.tsv \
    --denoised-copy-ratios /gatk/my_data/step4_DenoiseReadCounts/${NAME}.denoisedCR.tsv \
    --sequence-dictionary /gatk/hg38//Homo_sapiens_assembly38.dict \
    --minimum-contig-length 46709983 \
    --output /gatk/my_data/step5_PlotDenoisedCopyRatios/ \
    --output-prefix ${NAME}  2> $OUTPUT_DIR/step5_PlotDenoisedCopyRatios/$NAME.log
}
export -f step5_PlotDenoisedCopyRatios_DOCKER

step6_CollectAllelicCounts (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step6_CollectAllelicCounts para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}


  ${GATK} --java-options "-Xmx${MAXmem}G" CollectAllelicCounts \
    -L $OUTPUT_DIR/step1_PreprocessIntervals/targets.preprocessed.interval_list \
    -I $SAMPLE \
    -R ${REF_FASTA}/Homo_sapiens_assembly38.fasta \
    -O $OUTPUT_DIR/step6_CollectAllelicCounts/${NAME}.allelicCounts.tsv  2> $OUTPUT_DIR/step6_CollectAllelicCounts/$NAME.log
}
export -f step6_CollectAllelicCounts

step7_ModelSegments (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step7_ModelSegments para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}


  ${GATK} --java-options "-Xmx${MAXmem}G" ModelSegments \
     --denoised-copy-ratios $OUTPUT_DIR/step4_DenoiseReadCounts/${NAME}.denoisedCR.tsv  \
     --allelic-counts  $OUTPUT_DIR/step6_CollectAllelicCounts/${NAME}.allelicCounts.tsv \
     --output-prefix ${NAME} \
     -O $OUTPUT_DIR/step7_ModelSegments/  2> $OUTPUT_DIR/step7_ModelSegments/$NAME.log
}
export -f step7_ModelSegments

step8_CallCopyRatioSegments (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step8_CallCopyRatioSegments para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}


  ${GATK} --java-options "-Xmx${MAXmem}G" CallCopyRatioSegments \
    --input $OUTPUT_DIR/step7_ModelSegments/${NAME}.cr.seg \
    --output $OUTPUT_DIR/step8_CallCopyRatioSegments/${NAME}.called.seg  2> $OUTPUT_DIR/step8_CallCopyRatioSegments/$NAME.log
}
export -f step8_CallCopyRatioSegments

step9_PlotModeledSegments (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step9_PlotModeledSegments para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}

  ${GATK} --java-options "-Xmx${MAXmem}G" PlotModeledSegments \
    --denoised-copy-ratios  $OUTPUT_DIR/step4_DenoiseReadCounts/${NAME}.denoisedCR.tsv  \
    --allelic-counts $OUTPUT_DIR/step7_ModelSegments/${NAME}.hets.tsv \
    --segments $OUTPUT_DIR/step7_ModelSegments/${NAME}.modelFinal.seg \
    --sequence-dictionary ${REF_FASTA}/Homo_sapiens_assembly38.dict \
    --minimum-contig-length 46709983 \
    --output $OUTPUT_DIR/step9_PlotModeledSegments/ \
    --output-prefix ${NAME}  2> $OUTPUT_DIR/step9_PlotModeledSegments/$NAME.log
}
export -f step9_PlotModeledSegments

step9_PlotModeledSegments_DOCKER (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step9_PlotModeledSegments_DOCKER para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}


  docker run \
    --rm \
    -v $OUTPUT_DIR/:/gatk/my_data \
    -v ${REF_FASTA}:/gatk/hg38/ \
    -u $(id -u):$(id -g) broadinstitute/gatk \
    gatk --java-options "-Xmx${MAXmem}G" PlotModeledSegments \
    --denoised-copy-ratios  /gatk/my_data/step4_DenoiseReadCounts/${NAME}.denoisedCR.tsv  \
    --allelic-counts /gatk/my_data/step7_ModelSegments/${NAME}.hets.tsv \
    --segments /gatk/my_data/step7_ModelSegments/${NAME}.modelFinal.seg \
    --sequence-dictionary /gatk/hg38/Homo_sapiens_assembly38.dict \
    --minimum-contig-length 46709983 \
    --output /gatk/my_data/step9_PlotModeledSegments/ \
    --output-prefix ${NAME}  2>  $OUTPUT_DIR/step9_PlotModeledSegments/$NAME.log

  # docker run \
  # -v /home/scratch60/vlira_20nov2023/Result_Gatk-CNV.2023-11-07:/gatk/my_data \
  # -v /home/projects2/LIDO/molPathol/oncoseek/nextseq/hg38/:/gatk/hg38/ \
  # -u $(id -u):$(id -g) broadinstitute/gatk \
  # gatk PlotModeledSegments \
  # --denoised-copy-ratios /gatk/my_data/step4_DenoiseReadCounts/ROP-94-ExC85-xgenV2_S62.dedup.tags.bqsr.bam.denoisedCR.tsv \
  # --allelic-counts /gatk/my_data/step7_ModelSegments/ROP-94-ExC85-xgenV2_S62.dedup.tags.bqsr.bam.hets.tsv \
  # --segments /gatk/my_data/step7_ModelSegments/ROP-94-ExC85-xgenV2_S62.dedup.tags.bqsr.bam.modelFinal.seg \
  # --sequence-dictionary /gatk/hg38/Homo_sapiens_assembly38.dict \
  # --minimum-contig-length 46709983 \
  # --output /gatk/my_data/step9_PlotModeledSegments/ \
  # --output-prefix ROP-94-ExC85-xgenV2_S62.dedup.tags.bqsr.bam

  #docker run -v /home/scratch60/vlira_20nov2023/Result_Gatk-CNV.2023-11-07:/gatk/my_data -v /home/projects2/LIDO/molPathol/oncoseek/nextseq/hg38/:/gatk/hg38/ -it -u $(id -u):$(id -g) broadinstitute/gatk
}
export -f step9_PlotModeledSegments_DOCKER


step10_FilterCallCopyRatioSegments (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"
  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step10_FilterCallCopyRatioSegments para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}

  
  COPY_RATIO=5
  CUTOFF_AMP=0.5
  CUTOFF_DEL=-1

  grep -v "^chr" $OUTPUT_DIR/step8_CallCopyRatioSegments/${NAME}.called.seg > $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/${NAME}.called.filt.seg
  # grep "^chr" $OUTPUT_DIR/step8_CallCopyRatioSegments/${NAME}.called.seg | awk -F "\t" '{ if(($5 <= ${CUTOFF_DEL} || $5 >= ${CUTOFF_AMP} ) && ($4 > ${COPY_RATIO})) print $_}' >> $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/${NAME}.called.filt.seg
  grep "^chr" $OUTPUT_DIR/step8_CallCopyRatioSegments/${NAME}.called.seg | awk -F "\t" '{ if(($5 <= -1 || $5 >= 0.5 ) && ($4 > 5)) print $0}' >> $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/${NAME}.called.filt.seg

  grep -v "^ROP" $OUTPUT_DIR/step8_CallCopyRatioSegments/${NAME}.called.igv.seg > $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/${NAME}.called.filt.igv.seg
  grep "^ROP" $OUTPUT_DIR/step8_CallCopyRatioSegments/${NAME}.called.igv.seg | awk -F "\t" '{ if(($7 <= -1 || $7 >= 0.5 ) && ($5 > 5)) print $0}' >> $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/${NAME}.called.filt.igv.seg

}
export -f step10_FilterCallCopyRatioSegments

 dataSourcesFolder="/home/scratch90/vlira_05ago2024/references/funcotator_dataSources.v1.8.hg38.20230908s/"
# GATK="/home/scratch90/vlira_05ago2024/tools/gatk-4.6.0.0/./gatk"
# REF_FASTA="/home/projects2/LIDO/molPathol/oncoseek/nextseq/hg38/"
# OUTPUT_DIR="/home/scratch90/vlira_05ago2024/Result_Gatk-CNV.2023-11-07/"
# mkdir "${OUTPUT_DIR}/step10_FuncotateSegments/"
# NAME="ROP-98-ExC85-xgenV2_S66.dedup.tags.bqsr.bam"

step10_FuncotateSegments (){
  local SAMPLE=$1
  local NAME="${SAMPLE##*/}"

  echo "" >> ${LOG_FILE}
  echo ">>>>>> Executando step10_FuncotateSegments para Amostra: "$NAME" <<<  $(date) " >> ${LOG_FILE}


  ${GATK} FuncotateSegments \
    --data-sources-path ${dataSourcesFolder} \
    --ref-version hg38 \
    --output-file-format SEG \
    -R  ${REF_FASTA}/Homo_sapiens_assembly38.fasta \
    --segments $OUTPUT_DIR/step8_CallCopyRatioSegments/${NAME}.called.seg \
    -O ${OUTPUT_DIR}/step10_FuncotateSegments/${NAME}.funcotated.tsv 2> ${OUTPUT_DIR}/step10_FuncotateSegments/${NAME}.log2
  # --transcript-list tx_list.txt 
}
export -f step10_FuncotateSegments



echo "            >>>>>> Starting Pipeline to Run GATK-GermlineCNV  <<<<<< $(date) " > ${LOG_FILE}


ls ${INPUT_BAMS}/*.dedup.tags.bqsr.bam.cram > ${OUTPUT_DIR}/samples.list
grep -f /home/users/vlira/71samples.txt ${OUTPUT_DIR}/samples.list > ${OUTPUT_DIR}/samples_filtered.list
mv ${OUTPUT_DIR}/samples_filtered.list ${OUTPUT_DIR}/samples.list
export SAMPLE_LIST_BAM="${OUTPUT_DIR}/samples.list"


mkdir $OUTPUT_DIR/step1_PreprocessIntervals/
# step1_PreprocessIntervals

mkdir $OUTPUT_DIR/step2_AnnotateIntervals/
# step2_AnnotateIntervals

mkdir $OUTPUT_DIR/step3_CollectReadCounts/
# xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step3_CollectReadCounts  "$@"' 'step3_CollectReadCounts'


     # gatk FilterIntervals \
     #      -L preprocessed_intervals.interval_list \
     #      -XL blacklist_intervals.interval_list \
     #      -I sample_1.counts.hdf5 \
     #      -I sample_2.counts.hdf5 \
     #      ... \
     #      --annotated-intervals annotated_intervals.tsv \
     #      -O filtered_intervals.interval_list
 


mkdir $OUTPUT_DIR/step4_DenoiseReadCounts/
# xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step4_DenoiseReadCounts  "$@"' 'step4_DenoiseReadCounts'

mkdir $OUTPUT_DIR/step5_PlotDenoisedCopyRatios/
# #xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step5_PlotDenoisedCopyRatios  "$@"' 'step5_PlotDenoisedCopyRatios'
# xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step5_PlotDenoisedCopyRatios_DOCKER  "$@"' 'step5_PlotDenoisedCopyRatios_DOCKER'

mkdir $OUTPUT_DIR/step6_CollectAllelicCounts/
# xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step6_CollectAllelicCounts  "$@"' 'step6_CollectAllelicCounts'

mkdir $OUTPUT_DIR/step7_ModelSegments/
# xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step7_ModelSegments  "$@"' 'step7_ModelSegments'

mkdir $OUTPUT_DIR/step8_CallCopyRatioSegments/
# xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step8_CallCopyRatioSegments  "$@"' 'step8_CallCopyRatioSegments'

cat  $OUTPUT_DIR/step8_CallCopyRatioSegments/ROP-*.called.igv.seg | grep "Sample"| head -1 > $OUTPUT_DIR/step8_CallCopyRatioSegments/ALL-ROP.called.igv.seg
cat  $OUTPUT_DIR/step8_CallCopyRatioSegments/ROP-*.called.igv.seg | grep -v "Sample" >> $OUTPUT_DIR/step8_CallCopyRatioSegments/ALL-ROP.called.igv.seg

mkdir $OUTPUT_DIR/step9_PlotModeledSegments/
# # xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step9_PlotModeledSegments  "$@"' 'step9_PlotModeledSegments'
# xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step9_PlotModeledSegments_DOCKER  "$@"' 'step9_PlotModeledSegments_DOCKER'

# mkdir $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/
# xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step10_FilterCallCopyRatioSegments  "$@"' 'step10_FilterCallCopyRatioSegments'

# cat  $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/ROP-*.called.filt.igv.seg | grep "Sample"| head -1 > $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/ALL-ROP.called.filt.igv.seg
# cat  $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/ROP-*.called.filt.igv.seg | grep -v "Sample" >> $OUTPUT_DIR/step10_FilterCallCopyRatioSegments/ALL-ROP.called.filt.igv.seg

mkdir $OUTPUT_DIR/step10_FuncotateSegments/
xargs -a $OUTPUT_DIR/samples.list -t -n1 -P${JOBS} bash -c 'step10_FuncotateSegments  "$@"' 'step10_FuncotateSegments'


# 6- REUNI OS ARQUIVOS ANOTADOS EM UMA UNICA TABELA
SAMPLES=$(find $OUTPUT_DIR/step10_FuncotateSegments/ -maxdepth 1 -mindepth 1  -name '*.dedup.tags.bqsr.bam.funcotated.tsv.gene_list.txt')
echo > $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.gene_list.txt
echo > $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.funcotated.tsv
for SAMPLE in $SAMPLES; do
  NAME="${SAMPLE##*/}"
  echo ${NAME%.dedup*}
  cut -f 1,2,3,4,7,10,11,12  $OUTPUT_DIR/step10_FuncotateSegments/${NAME%.dedup*}.dedup.tags.bqsr.bam.funcotated.tsv.gene_list.txt| awk -OFS="\t" -v N=${NAME%.dedup*} '{print N,$_ }' >> $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.gene_list.txt
  cut -f 3,5,8,9,11,15,17,18,19,20,21  $OUTPUT_DIR/step10_FuncotateSegments/${NAME%.dedup*}.dedup.tags.bqsr.bam.funcotated.tsv| awk -OFS="\t" -v N=${NAME%.dedup*} '{print N,$_ }'  >> $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.funcotated.tsv
done

# TABELA RESULTADO FINAL 
sed -i 's/\s/\t/' $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.funcotated.tsv
sed -i 's/\s/\t/'  $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.gene_list.txt

# cut -f 1,2,3,4,7,10,11,12  $OUTPUT_DIR/step10_FuncotateSegments/ROP-*.dedup.tags.bqsr.bam.funcotated.tsv.gene_list.txt | grep "sample"| head -1 > $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.gene_list.txt
# cut -f 1,2,3,4,7,10,11,12  $OUTPUT_DIR/step10_FuncotateSegments/ROP-*.dedup.tags.bqsr.bam.funcotated.tsv.gene_list.txt | grep -v "sample" >> $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.gene_list.txt

# cut -f 3,5,7,8,9,11,15,17,18,19,20,21  $OUTPUT_DIR/step10_FuncotateSegments/ROP-*.dedup.tags.bqsr.bam.funcotated.tsv | grep "sample"| head -1 > $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.funcotated.tsv
# cut -f 3,5,7,8,9,11,15,17,18,19,20,21  $OUTPUT_DIR/step10_FuncotateSegments/ROP-*.dedup.tags.bqsr.bam.funcotated.tsv | grep -v "sample" >> $OUTPUT_DIR/step10_FuncotateSegments/ALL-ROP.funcotated.tsv


echo "" >> ${LOG_FILE}
echo "                           >>>>>> End Pipeline <<< " >> ${LOG_FILE}
date >> ${LOG_FILE}
echo "" >> ${LOG_FILE}
